spring:
  aplication:
    name: gateway-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gg?characterEncoding=UTF-8&amp;serverTimezone=UTC&amp;useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/authorization/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
  thymeleaf:
    cache: false
server:
  port: 8888
  servlet:
    context-path: /gateway
username:
  frank: frank1
address:
  china: china1